version: '3.5'
services:
    nginx:
        container_name: docker-proxy-nginx
        image: wizaplaceglobal.azurecr.io/docker-proxy/docker-proxy-nginx:${NGINX_VERSION:-latest}
        restart: unless-stopped
        ports:
            - ${HTTP_PORT:-80}:80
            - ${HTTPS_PORT:-443}:443
        volumes:
            - virtual_host:/etc/nginx/conf.d
            - homepage:/var/www/homepage
            - certificates:/etc/nginx/certificates:ro

    proxy:
        container_name: docker-proxy-cli
        image: wizaplaceglobal.azurecr.io/docker-proxy/docker-proxy-${PROXY_PROVIDER:-php}:${PROXY_PROVIDER_VERSION:-latest}
        restart: unless-stopped
        environment:
            HTTP_PORT: ${HTTP_PORT:-80}
            HTTPS_PORT: ${HTTPS_PORT:-443}
            VIRTUAL_HOST_DIRECTORY: /etc/nginx/conf.d
            HOMEPAGE_DIRECTORY: /var/www/homepage
            CERTIFICATE_DIRECTORY: /etc/nginx/certificates
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - virtual_host:/etc/nginx/conf.d
            - homepage:/var/www/homepage
            - certificates:/etc/nginx/certificates

volumes:
    virtual_host:
    homepage:
    certificates:
